---
title: "Introdução"
---

Cada ser humano é único. Cada um de nós tem uma história diferente, um conjunto particular de conhecimentos, de crenças, de sentimentos e de emoções. A busca por compreender esses diferentes padrões de comportamento é uma antiga pretensão dos filósofos e cientistas. Esse conjunto de características únicas que distinguem o indivíduo, seu padrão particular de comportamento e atitudes diante da vida e nos relacionamentos com os outros é o que usualmente denominamos de **Personalidade**. Entretanto, o repertório de comportamentos e sentimentos humano é bastante extenso. Determinar quais as dimensões desses fenômenos serão levadas em consideração e analisadas é uma decisão complexa.

Uma das primeiras tentativas de classificar os diversos tipos de comportamentos em grupos remonta aos filósofos gregos, que tentaram capturar e organizar as diferenças individuais de comportamentos e emoções para entender a personalidade humana. A medicina da escola hipocrático-galênica descrevia quatro temperamentos, entendidos como disposições características que influenciavam a forma como as ações das pessoas se expressavam: sanguíneo, fleumático, colérico e melancólico [@dalgalarrondo_personalidade_2008; @stelmack_galen_1991]. Essas concepções perduraram por mais de 1.500 anos, influenciando desde Kant a Wundt no século XVIII [@stelmack_galen_1991].

Entretanto, a despeito das inúmeras tentativas de descrever quais seriam essas diferentes dimensões de personalidade, esse tema ainda é bastante controverso. O estudo da personalidade compreende um grande número de diferentes teorias e diferentes metodologias de pesquisa [@corr_cambridge_2009]. Ao longo do último século, diferentes teorias competiram para descrever e explicar o comportamento humano (psicodinâmicas, comportamentais, humanísticas, cognitivas, biológicas etc.). Mas o que emerge de comum em todas essas teorias é o entendimento de que a personalidade de um indivíduo começa com componentes inatos que, ao longo da vida, sofrem influência de diversos fatores — incluindo experiências individuais, familiares e culturais — e que resultam num padrão de comportamentos, pensamentos e emoções que constituem o que chamamos de personalidade [@cloninger_conceptual_2009].

Além dessas diferentes abordagens teóricas, o estudo da personalidade também se diferencia no que se refere aos métodos de investigação. Ao longo da história da psicologia, dois métodos competem para a obtenção de dados, criando duas correntes dicotômicas: aqueles que se abrem a analisar a experiência humana em sua subjetividade e aqueles que enfatizam os métodos científicos rigorosos. Por um lado, abordagens **idiográficas** estudam o indivíduo; por outro, abordagens **nomotéticas** procuram generalizações e comparações baseadas no estudo de grupos de pessoas. Apesar de conflitos e tensões, essas abordagens se complementam, e o estudo da personalidade necessita de ambas [@cloninger_conceptual_2009].
